N200 = ["ACC", "AUBANK", "AARTIIND", "ABBOTINDIA", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ATGL", "ADANITRANS",
        "ABCAPITAL", "ABFRL", "AJANTPHARM", "APLLTD","AMARAJABAT","AMBUJACEM","APOLLOHOSP","APOLLOTYRE",
        "ASHOKLEY","ASIANPAINT","AUROPHARMA","DMART","AXISBANK","BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BAJAJHLDNG",
        "BALKRISIND","BANDHANBNK","BANKBARODA","BATAINDIA","BERGEPAINT","BEL","BHARATFORG","BHEL","BPCL",
        "BHARTIARTL","BIOCON","BBTC","BOSCHLTD","BRITANNIA","CADILAHC","CANBK","CASTROLIND","CHOLAFIN","CIPLA",
        "CUB","COALINDIA","COFORGE","COLPAL","CONCOR","CUMMINSIND","DLF","DABUR","DALBHARAT",
        "DEEPAKNTR","DIVISLAB","DIXON","LALPATHLAB","DRREDDY","EICHERMOT","ESCORTS",
        "EXIDEIND","FEDERALBNK","GAIL","GMRINFRA","GLAND","GLENMARK","GODREJCP","GODREJIND",
        "GODREJPROP", "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE",
        "HEROMOTOCO", "HINDALCO", "HAL", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HDFC", "ICICIBANK", "ICICIGI",
        "ICICIPRULI", "ISEC", "IDFCFIRSTB", "ITC", "IBULHSGFIN", "INDIAMART", "INDHOTEL", "IOC", "IRCTC",
        "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY", "INDIGO", "IPCALAB", "JSWENERGY", "JSWSTEEL", "JINDALSTEL",
        "JUBLFOOD", "KOTAKBANK", "LTTS", "LICHSGFIN", "LTI", "LT", "LAURUSLABS", "LUPIN",
        "M&M", "MARICO", "MARUTI", "MINDTREE", "MPHASIS", "MUTHOOTFIN", "NATCOPHARM",
        "NMDC", "NTPC", "NAVINFLUOR", "NESTLEIND", "NAM-INDIA", "ONGC", "OIL", "PIIND", "PAGEIND",
         "PFIZER", "PIDILITIND", "PEL", "POLYCAB", "PFC", "POWERGRID", "PRESTIGE", "PNB",
        "RBLBANK", "RELIANCE", "SBICARD", "SBILIFE", "SRF", "SHREECEM", "SRTRANSFIN",
         "SBIN", "SAIL", "SUNPHARMA", "SUNTV","TVSMOTOR", "TATACHEM", "TCS", "TATACONSUM",
        "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TECHM", "RAMCOCEM", "TITAN", "TORNTPHARM", "TORNTPOWER",
        "TRENT", "UPL", "ULTRACEMCO", "UNIONBANK", "UBL", "MCDOWELL-N", "VBL", "VEDL", "IDEA", "VOLTAS",
       "WIPRO", "YESBANK", "ZEEL"]


N100 = ["ACC", "ADANIENT","ADANIGREEN","ADANIPORTS","ADANITRANS","AMBUJACEM","APOLLOHOSP","ASIANPAINT","AUROPHARMA",
        "DMART", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "BANDHANBNK", "BANKBARODA",
        "BERGEPAINT", "BPCL", "BHARTIARTL", "BIOCON", "BOSCHLTD", "BRITANNIA", "CADILAHC", "CHOLAFIN", "CIPLA",
        "COALINDIA", "COLPAL", "DLF", "DABUR", "DIVISLAB", "DRREDDY", "EICHERMOT", "GAIL", "GLAND", "GODREJCP",
        "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HAVELLS", "HEROMOTOCO", "HINDALCO", "HINDPETRO",
        "HINDUNILVR", "HDFC", "ICICIBANK", "ICICIGI", "ICICIPRULI", "ITC", "IOC", "IGL", "INDUSTOWER", "INDUSINDBK",
        "NAUKRI", "INFY", "INDIGO", "JSWSTEEL", "JINDALSTEL", "JUBLFOOD", "KOTAKBANK", "LTI", "LT", "LUPIN", "M&M",
        "MARICO", "MARUTI", "MUTHOOTFIN", "NMDC", "NTPC", "NESTLEIND", "ONGC", "PIIND", "PIDILITIND", "PEL", "POWERGRID",
        "PGHH", "PNB", "RELIANCE", "SBICARD", "SBILIFE", "SHREECEM", "SIEMENS", "SBIN", "SAIL", "SUNPHARMA", "TCS",
        "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TECHM", "TITAN", "TORNTPHARM", "UPL", "ULTRACEMCO", "MCDOWELL-N",
        "VEDL", "WIPRO", "YESBANK",]

N50 = ["ADANIPORTS","ASIANPAINT","AXISBANK","BAJAJFINSV","BAJFINANCE","BHARTIARTL","BPCL","BRITANNIA","CIPLA",
       "COALINDIA","DIVISLAB","DRREDDY","EICHERMOT","GRASIM","HCLTECH","HDFC","HDFCBANK","HDFCLIFE","HEROMOTOCO","HINDALCO",
       "HINDUNILVR","ICICIBANK","INDUSINDBK","INFY","IOC","ITC","JSWSTEEL","KOTAKBANK","LT","M&M","MARUTI","NESTLEIND",
       "NTPC","ONGC","POWERGRID","RELIANCE","SBILIFE","SBIN","SHREECEM","SUNPHARMA","TATACONSUM","TATAMOTORS","TATASTEEL",
       "TCS","TECHM","TITAN","ULTRACEMCO","UPL","WIPRO"]

Test = ["ADANIPORTS", "ASIANPAINT", "AXISBANK","BAJAJ-AUTO","BAJAJFINSV"]#,"BAJFINANCE","BHARTIARTL","BPCL","BRITANNIA",
      #  "CIPLA","SBIN","SHREECEM","SUNPHARMA","INDUSINDBK","INFY","IOC","ITC","JSWSTEEL","KOTAKBANK","LT","M&M","MARUTI",
      #  "NESTLEIND"]


BroadMarketIndices = ["NIFTY 50",
                      "NIFTY 100",
                      "NIFTY 500",
                      "INDIA VIX",
                      "NIFTY MIDCAP 50",
                      "NIFTY NEXT 50",
                      "NIFTY MIDCAP 100",
                      "NIFTY MIDCAP 150",
                      "NIFTY SERV SECTOR",
                      "NIFTY LARGEMID250",
                      "NIFTY SMLCAP 50",
                      "NIFTY SMLCAP 100"]

SectoralIndices = ["NIFTY IT","NIFTY BANK","NIFTY INFRA","NIFTY REALTY","NIFTY CONSUMPTION",
                   "NIFTY MNC",
                   "NIFTY PVT BANK",
                   "NIFTY OIL AND GAS",
                   "NIFTY PHARMA",
                   "NIFTY CPSE",
                   "NIFTY FMCG",
                   "NIFTY AUTO",
                   "NIFTY PSE",
                   "NIFTY PSU BANK",
                   "NIFTY CONSR DURBL",
                   "NIFTY ENERGY",
                   "NIFTY METAL",
                   "NIFTY FIN SERVICE",
                   "NIFTY HEALTHCARE",
                   "NIFTY MEDIA"]

ThematicIndices = ["NIFTY500 SHARIAH",
                   "NIFTY50 SHARIAH",
                   "NIFTY ADITYA BIRLA GROUP",
                   "NIFTY MAHINDRA GROUP",
                   "NIFTY TATA GROUP",
                   "NIFTY TATA GROUP 25% CAP",
                   "NIFTY SHARIAH 25",
                   "NIFTY 50 FUTURES INDEX",
                   "NIFTY 50 FUTURES TR INDEX",
                   "NIFTY 50 ARBITRAGE",
                   "NIFTY QUALITY LOW-VOLATILITY 30",
                   "NIFTY ALPHA QUALITY LOW-VOLATILITY 30",
                   "NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30",
                   "NIFTY500 VALUE 50",
                   "NIFTY100 ENHANCED ESG",
                   "NIFTY100 ESG",
                   "NIFTY INDIA MANUFACTURING",
                   "NIFTY MIDCAP SELECT",
                   "NIFTY TOTAL MARKET",
                   "NIFTY NON-CYCLICAL CONSUMER",
                   "NIFTY50 USD",
                   "NIFTY 1D RATE INDEX",
                   "NIFTY 10 YEAR SDL INDEX",
                   "NIFTY BHARAT BOND INDEX - APRIL 2023",
                   "NIFTY BHARAT BOND INDEX - APRIL 2030",
                   "NIFTY BHARAT BOND INDEX - APRIL 2025",
                   "NIFTY BHARAT BOND INDEX - APRIL 2031"]



URL = "https://in.tradingview.com/chart/gCiOEGU4/?symbol=NSE:"


